//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18010
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sol2Reg.GuiModule.Base
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Contexte pour l'application RIA.
    /// </summary>
    /// <remarks>
    /// Ce contexte étend la base pour rendre les services d'application et types disponibles
    /// pour utilisation à partir du code et de xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Définitions de méthodes d'extensibilité

        /// <summary>
        /// Cette méthode est appelée à partir du constructeur une fois l'initialisation terminée et
        /// peut être utilisée pour une autre configuration d'objet.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initialise une nouvelle instance de la classe WebContext.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Obtient le contexte qui est inscrit en tant qu'objet de durée de vie auprès de l'application actuelle.
        /// </summary>
        /// <exception cref="InvalidOperationException"> est levée s'il n'existe aucune application actuelle,
        /// si aucun contexte n'a été ajouté ou si plusieurs contextes ont été ajoutés.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
